let menu = [
	{
		text: "HTML",
		data: [{
				id: "00-basic",
				text: "基本架構",
				context: "lesson00.t.html",
				html: "lesson00.html",
				css: "style.css",
				js: "system.js"
			}, {
				id: "01-block",
				text: "區塊/標題",
				context: "lesson01.t.html",
				html: "lesson01.html",
			}, {
				id: "02-ul",
				text: "項目清單",
				context: "lesson02.t.html",
				html: "lesson02.html",
			}, {
				id: "03-img",
				text: "圖片和超連結",
				context: "lesson03.t.html",
				html: "lesson03.html",
			}, {
				id: "04-font",
				text: "字體",
				context: "lesson04.t.html",
				html: "lesson04.html",				
			}, {
				id: "05-table",
				text: "表格",
				context: "lesson05.t.html",
				html: "lesson05.html",
			}, {
				id: "06-form",
				text: "表單",
				context: "lesson06.t.html",
				html: "lesson06.html",	
			}, {
				id: "07-iframe",
				text: "框窗",
				context: "lesson07.t.html",
				html: "lesson07.html",	
			}, {
				id: "08-event",
				text: "事件",
				context: "lesson08.t.html",
				html: "lesson08.html",	
			}, {
				id: "09-color",
				text: "顏色",
				context: "lesson09.t.html",
				html: "lesson09.html"
			}
		] //
	}, {
		text: "CSS",
		data: [{
			id: "00-basic",
			text: "基本架構",
			context: "lesson00.t.html",
			html: "lesson00.html",
		}, {
			id: "01-selector",
			text: "選擇器",
			children: [{
				id: "011-selector",
				text: "選擇器-1",
				context: "lesson011.t.html",
				html: "lesson011.html",
			}, {
				id: "012-selector",
				text: "選擇器-2",
				context: "lesson012.t.html",
				html: "lesson012.html",
			}, {
				id: "013-selector",
				text: "選擇器-3",
				context: "lesson013.t.html",
				html: "lesson013.html",
			}]
		}]
	}, {
		text: "JavaScript",
		data: [{
			id: "00-basic",
			text: "基本架構",
			context: "lesson00.t.html",
			html: "lesson00.html",
		}]
	}, {
		text: "作業",
		data: []
	}
];
